//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpDb.EntityFrameworkCore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpDb.EntityFrameworkCore.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command has no associated connection..
        /// </summary>
        internal static string Text_Error_Command_MissingConnection {
            get {
                return ResourceManager.GetString("Text.Error.Command.MissingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The `{0}` repository ({1}) does not support `Add` operation..
        /// </summary>
        internal static string Text_Error_Repository_AddNotSupported {
            get {
                return ResourceManager.GetString("Text.Error.Repository.AddNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The `{0}` repository ({1}) does not support `Remove` operation..
        /// </summary>
        internal static string Text_Error_Repository_DeleteNotSupported {
            get {
                return ResourceManager.GetString("Text.Error.Repository.DeleteNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The `{0}` repository ({1}) does not support `Update` operation..
        /// </summary>
        internal static string Text_Error_Repository_UpdateNotSupported {
            get {
                return ResourceManager.GetString("Text.Error.Repository.UpdateNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one records returned..
        /// </summary>
        internal static string Text_Error_Sql_MoreThanOneRow {
            get {
                return ResourceManager.GetString("Text.Error.Sql.MoreThanOneRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records returned..
        /// </summary>
        internal static string Text_Error_Sql_NoRows {
            get {
                return ResourceManager.GetString("Text.Error.Sql.NoRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current transaction has no associated connection..
        /// </summary>
        internal static string Text_Error_Transaction_MissingConnection {
            get {
                return ResourceManager.GetString("Text.Error.Transaction.MissingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type `{0}` could not be constructed..
        /// </summary>
        internal static string Text_Error_TypeInstantiationFailed {
            get {
                return ResourceManager.GetString("Text.Error.TypeInstantiationFailed", resourceCulture);
            }
        }
    }
}
