//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpDb.EntityFrameworkCore {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SharpDb.EntityFrameworkCore.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Text_Error_Command_MissingConnection {
            get {
                return ResourceManager.GetString("Text.Error.Command.MissingConnection", resourceCulture);
            }
        }
        
        internal static string Text_Error_Repository_AddNotSupported {
            get {
                return ResourceManager.GetString("Text.Error.Repository.AddNotSupported", resourceCulture);
            }
        }
        
        internal static string Text_Error_Repository_DeleteNotSupported {
            get {
                return ResourceManager.GetString("Text.Error.Repository.DeleteNotSupported", resourceCulture);
            }
        }
        
        internal static string Text_Error_Repository_UpdateNotSupported {
            get {
                return ResourceManager.GetString("Text.Error.Repository.UpdateNotSupported", resourceCulture);
            }
        }
        
        internal static string Text_Error_Sql_MoreThanOneRow {
            get {
                return ResourceManager.GetString("Text.Error.Sql.MoreThanOneRow", resourceCulture);
            }
        }
        
        internal static string Text_Error_Sql_NoRows {
            get {
                return ResourceManager.GetString("Text.Error.Sql.NoRows", resourceCulture);
            }
        }
        
        internal static string Text_Error_Transaction_MissingConnection {
            get {
                return ResourceManager.GetString("Text.Error.Transaction.MissingConnection", resourceCulture);
            }
        }
        
        internal static string Text_Error_TypeInstantiationFailed {
            get {
                return ResourceManager.GetString("Text.Error.TypeInstantiationFailed", resourceCulture);
            }
        }
        
        internal static string Text_Error_Repository_AttachNotSupported {
            get {
                return ResourceManager.GetString("Text.Error.Repository.AttachNotSupported", resourceCulture);
            }
        }
        
        internal static string Ordering_Undefined_PkOrIndex {
            get {
                return ResourceManager.GetString("Ordering_Undefined_PkOrIndex", resourceCulture);
            }
        }
    }
}
