//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpDb {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SharpDb.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Text_Error_DbDataReader_ColumnNotFound {
            get {
                return ResourceManager.GetString("Text.Error.DbDataReader.ColumnNotFound", resourceCulture);
            }
        }
        
        internal static string Text_Error_DbDataReader_ColumnValueIsNull {
            get {
                return ResourceManager.GetString("Text.Error.DbDataReader.ColumnValueIsNull", resourceCulture);
            }
        }
        
        internal static string Text_Error_DbDataReader_ColumnValueOutOfRange {
            get {
                return ResourceManager.GetString("Text.Error.DbDataReader.ColumnValueOutOfRange", resourceCulture);
            }
        }
        
        internal static string Text_Error_QueryParameter_EmptyName {
            get {
                return ResourceManager.GetString("Text.Error.QueryParameter.EmptyName", resourceCulture);
            }
        }
        
        internal static string Text_Error_QueryString_Empty {
            get {
                return ResourceManager.GetString("Text.Error.QueryString.Empty", resourceCulture);
            }
        }
        
        internal static string Text_Error_QueryString_InvalidFormat {
            get {
                return ResourceManager.GetString("Text.Error.QueryString.InvalidFormat", resourceCulture);
            }
        }
        
        internal static string Text_Error_QueryString_TagCommentedOut {
            get {
                return ResourceManager.GetString("Text.Error.QueryString.TagCommentedOut", resourceCulture);
            }
        }
        
        internal static string Text_Error_QueryString_TagNotFound {
            get {
                return ResourceManager.GetString("Text.Error.QueryString.TagNotFound", resourceCulture);
            }
        }
        
        internal static string Text_Error_DataType_ValueOutOfRange {
            get {
                return ResourceManager.GetString("Text.Error.DataType.ValueOutOfRange", resourceCulture);
            }
        }
        
        internal static string Text_Error_QueryParameter_TooManyAtSigns {
            get {
                return ResourceManager.GetString("Text.Error.QueryParameter.TooManyAtSigns", resourceCulture);
            }
        }
        
        internal static string Text_Error_DbDataReader_ColumnValueNotConvertable {
            get {
                return ResourceManager.GetString("Text.Error.DbDataReader.ColumnValueNotConvertable", resourceCulture);
            }
        }
        
        internal static string Text_Error_Comparison_IncompatibleTypes {
            get {
                return ResourceManager.GetString("Text.Error.Comparison.IncompatibleTypes", resourceCulture);
            }
        }
        
        internal static string Text_Error_Transaction_NoTransientErrorFound {
            get {
                return ResourceManager.GetString("Text.Error.Transaction.NoTransientErrorFound", resourceCulture);
            }
        }
    }
}
