//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpDb {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpDb.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be between {0} and {1} for type {2}..
        /// </summary>
        internal static string Text_Error_DataType_ValueOutOfRange {
            get {
                return ResourceManager.GetString("Text.Error.DataType.ValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column with name {0} was not found..
        /// </summary>
        internal static string Text_Error_DbDataReader_ColumnNotFound {
            get {
                return ResourceManager.GetString("Text.Error.DbDataReader.ColumnNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column with name {0} is NULL and cannot be converted to type {1}..
        /// </summary>
        internal static string Text_Error_DbDataReader_ColumnValueIsNull {
            get {
                return ResourceManager.GetString("Text.Error.DbDataReader.ColumnValueIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column with name {0} is of type {1} and cannot be converted to type {2}..
        /// </summary>
        internal static string Text_Error_DbDataReader_ColumnValueNotConvertable {
            get {
                return ResourceManager.GetString("Text.Error.DbDataReader.ColumnValueNotConvertable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column with name {0} is of type {1} and cannot be converted to type {2} due to range constraints..
        /// </summary>
        internal static string Text_Error_DbDataReader_ColumnValueOutOfRange {
            get {
                return ResourceManager.GetString("Text.Error.DbDataReader.ColumnValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter name cannot be empty or `@`..
        /// </summary>
        internal static string Text_Error_QueryParameter_EmptyName {
            get {
                return ResourceManager.GetString("Text.Error.QueryParameter.EmptyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter name cannot start with multiple `@` characters..
        /// </summary>
        internal static string Text_Error_QueryParameter_TooManyAtSigns {
            get {
                return ResourceManager.GetString("Text.Error.QueryParameter.TooManyAtSigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot use empty string as an SQL command..
        /// </summary>
        internal static string Text_Error_QueryString_Empty {
            get {
                return ResourceManager.GetString("Text.Error.QueryString.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String is not a valid SQL command ({0})..
        /// </summary>
        internal static string Text_Error_QueryString_InvalidFormat {
            get {
                return ResourceManager.GetString("Text.Error.QueryString.InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String contains `{0}` tag, but the tag is commented out..
        /// </summary>
        internal static string Text_Error_QueryString_TagCommentedOut {
            get {
                return ResourceManager.GetString("Text.Error.QueryString.TagCommentedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String does not contain `{0}` tag..
        /// </summary>
        internal static string Text_Error_QueryString_TagNotFound {
            get {
                return ResourceManager.GetString("Text.Error.QueryString.TagNotFound", resourceCulture);
            }
        }
    }
}
