<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <GenerateProgramFile>true</GenerateProgramFile>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="DbTypes.fs" />
    <Compile Include="UoWBenchmarksSmall.fs" />
    <Compile Include="UoWBenchmarksLarge.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="FSharp.Core" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SharpDb.EntityFrameworkCore\SharpDb.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\src\SharpDb\SharpDb.csproj" />
  </ItemGroup>

</Project>
